<?php

namespace Database\Seeders;

use App\Models\Tour;
use Illuminate\Database\Seeder;

class IngoingToursSeeder extends Seeder
{
    public function run(): void
    {
        Tour::where('type', 'ingoing')->delete();

        $defaultIncludes = ['Professional English-speaking guide', 'Air-conditioned transport', 'Bottled water', 'Hotel pickup & drop-off'];
        $defaultExcludes = ['Meals (unless specified)', 'Entry fees to monuments', 'Personal expenses', 'Travel insurance'];

        $tours = [
            [
                'title'       => 'Classic Yerevan City Tour',
                'slug'        => 'classic-yerevan-city',
                'region'      => 'yerevan',
                'description' => "Walk through the heart of one of the world's oldest cities. Visit Republic Square, the iconic Cascade complex, bustling Vernissage market, and enjoy stunning views of Mount Ararat.\n\nYour guide will share stories of Yerevan's 2,800-year history as you explore the pink-tuff architecture, vibrant cafes, and hidden courtyards of this unforgettable capital city.",
                'duration'    => '1 Day',
                'price_from'  => 35.00,
                'image_url'   => 'https://images.unsplash.com/photo-1558972250-100afca53bde?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1558972250-100afca53bde?w=800&q=80','https://images.unsplash.com/photo-1609946860441-a36e1e4b7587?w=800&q=80','https://images.unsplash.com/photo-1607962837359-5e7e89f86776?w=800&q=80','https://images.unsplash.com/photo-1617391654483-a07e77c08fa7?w=800&q=80'],
                'itinerary'   => [['title'=>'Republic Square & Opera House','description'=>'Start at the heart of Yerevan. Explore the grand Republic Square, see the singing fountains, and walk to the Armenian Opera House.'],['title'=>'The Cascade & Cafesjian Museum','description'=>'Climb the massive Cascade stairway with panoramic city views. Visit the Cafesjian Center for the Arts with modern sculptures.'],['title'=>'Vernissage Market & Blue Mosque','description'=>'Browse handmade crafts at Vernissage open-air market. Visit the 18th-century Blue Mosque, a symbol of cultural diversity.'],['title'=>'Matenadaran & Mount Ararat Views','description'=>'End at Matenadaran, the ancient manuscripts museum, with breathtaking views of Mount Ararat.']],
                'includes'    => ['Professional guide', 'Walking tour (4-5 hours)', 'Hotel pickup & drop-off', 'Bottled water'],
                'excludes'    => ['Meals', 'Museum entry fees (~$3-5)', 'Personal expenses'],
            ],
            [
                'title'       => 'Garni Temple & Geghard Monastery',
                'slug'        => 'garni-geghard',
                'region'      => 'kotayk',
                'description' => "Visit the only Greco-Roman pagan temple in the Caucasus and the UNESCO-listed Geghard Monastery, partially carved out of rock. Enjoy the scenic Azat River gorge with its famous Symphony of Stones basalt columns.\n\nThis tour combines Armenia's pagan and Christian heritage in one unforgettable day, just 30 minutes from Yerevan.",
                'duration'    => '1 Day',
                'price_from'  => 40.00,
                'image_url'   => 'https://images.unsplash.com/photo-1600959907703-125ba1374a12?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1600959907703-125ba1374a12?w=800&q=80','https://images.unsplash.com/photo-1569949237615-e1268f0b311b?w=800&q=80','https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80'],
                'itinerary'   => [['title'=>'Garni Temple','description'=>'Explore the beautifully restored 1st-century Hellenistic temple overlooking the Azat River gorge.'],['title'=>'Symphony of Stones','description'=>'Walk down to see the spectacular natural basalt organ-pipe columns along the gorge.'],['title'=>'Geghard Monastery','description'=>'Visit this UNESCO World Heritage Site, a medieval monastery partially carved from the rock face, known for incredible acoustics.']],
                'includes'    => $defaultIncludes,
                'excludes'    => $defaultExcludes,
            ],
            [
                'title'       => 'Lake Sevan & Sevanavank',
                'slug'        => 'lake-sevan-sevanavank',
                'region'      => 'gegharkunik',
                'description' => "Visit the \"Pearl of Armenia\" — Lake Sevan, one of the largest high-altitude freshwater lakes in the world at 1,900 meters. Explore the medieval Sevanavank monastery perched on a peninsula.\n\nEnjoy fresh fish lunch by the lake, swim in crystal-clear waters (summer), and visit the ancient Noratus cemetery with its field of carved khachkars.",
                'duration'    => '1 Day',
                'price_from'  => 45.00,
                'image_url'   => 'https://images.unsplash.com/photo-1603921288457-0a30e11e7db8?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1603921288457-0a30e11e7db8?w=800&q=80','https://images.unsplash.com/photo-1569949237615-e1268f0b311b?w=800&q=80'],
                'itinerary'   => [['title'=>'Sevanavank Monastery','description'=>'Visit the 9th-century monastery on the Sevan Peninsula with panoramic views of the lake and surrounding mountains.'],['title'=>'Lake Sevan Beach','description'=>'Relax by the lake, swim in summer, and enjoy a traditional Armenian fish lunch at a lakeside restaurant.'],['title'=>'Noratus Cemetery','description'=>'Explore the largest collection of khachkars (cross-stones) in Armenia, dating from the 10th to 17th centuries.']],
                'includes'    => $defaultIncludes,
                'excludes'    => ['Meals', 'Swimming equipment', 'Personal expenses'],
            ],
            [
                'title'       => 'Khor Virap & Mount Ararat Views',
                'slug'        => 'khor-virap-ararat',
                'region'      => 'ararat',
                'description' => "See the iconic Khor Virap monastery with Mount Ararat as its breathtaking backdrop — the most photographed scene in Armenia. Learn about the origins of Armenian Christianity at this sacred pilgrimage site.\n\nAccording to legend, Gregory the Illuminator was imprisoned here for 13 years before converting King Tiridates III, making Armenia the first Christian nation in 301 AD.",
                'duration'    => '1 Day',
                'price_from'  => 35.00,
                'image_url'   => 'https://images.unsplash.com/photo-1584646098378-0874589d76b1?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1584646098378-0874589d76b1?w=800&q=80','https://images.unsplash.com/photo-1590073242678-70ee3fc28e8e?w=800&q=80'],
                'itinerary'   => [['title'=>'Khor Virap Monastery','description'=>'Visit the monastery and descend into the underground pit where Gregory the Illuminator was held.'],['title'=>'Mount Ararat Views','description'=>'Photograph the stunning views of Mount Ararat, Armenia\'s national symbol, just across the border.'],['title'=>'Ararat Valley','description'=>'Drive through fertile vineyards and orchards of the Ararat Valley.']],
                'includes'    => $defaultIncludes,
                'excludes'    => $defaultExcludes,
            ],
            [
                'title'       => 'Noravank Monastery & Areni Winery',
                'slug'        => 'noravank-areni',
                'region'      => 'vayots_dzor',
                'description' => "Drive through stunning red rock canyons to the 13th-century Noravank monastery, a masterpiece of medieval Armenian architecture by Momik. Visit the Areni wine region, home to the world's oldest known winery — a 6,100-year-old cave.\n\nTaste Armenia's famous Areni red wines and enjoy the dramatic landscapes of Vayots Dzor.",
                'duration'    => '1 Day',
                'price_from'  => 50.00,
                'image_url'   => 'https://images.unsplash.com/photo-1569949237615-e1268f0b311b?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1569949237615-e1268f0b311b?w=800&q=80','https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80','https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=800&q=80'],
                'itinerary'   => [['title'=>'Areni-1 Cave','description'=>'Visit the cave where the world\'s oldest leather shoe and winery were discovered.'],['title'=>'Noravank Monastery','description'=>'Explore the 13th-century monastery set in a dramatic red cliff canyon. Climb the narrow steps of the Burtelashen Church.'],['title'=>'Wine Tasting','description'=>'Visit a local winery for a tasting of Areni grape wines, Armenia\'s signature variety.']],
                'includes'    => array_merge($defaultIncludes, ['Wine tasting']),
                'excludes'    => ['Lunch', 'Personal expenses'],
            ],
            [
                'title'       => 'Tatev Monastery & Wings of Tatev',
                'slug'        => 'tatev-monastery',
                'region'      => 'syunik',
                'description' => "Ride the world's longest reversible aerial tramway — Wings of Tatev (5.7 km) — to Tatev Monastery, perched on a cliff edge above the Vorotan Gorge. Explore the medieval monastery complex with its swaying pillar and enjoy spectacular views.\n\nThis two-day adventure through southern Armenia includes the spa town of Jermuk and the dramatic landscapes of Syunik.",
                'duration'    => '2 Days',
                'price_from'  => 120.00,
                'image_url'   => 'https://images.unsplash.com/photo-1608746249753-9346e2dca7c0?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1608746249753-9346e2dca7c0?w=800&q=80','https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=800&q=80','https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80'],
                'itinerary'   => [['title'=>'Day 1: Jermuk & Vorotan Gorge','description'=>'Drive to the spa town of Jermuk. Visit the Jermuk waterfall and the Devil\'s Bridge natural formation.'],['title'=>'Day 2: Wings of Tatev & Monastery','description'=>'Ride the record-breaking aerial tramway over the gorge. Explore Tatev Monastery, one of Armenia\'s greatest medieval seats of learning.']],
                'includes'    => array_merge($defaultIncludes, ['1 night hotel in Goris', 'Breakfast', 'Tramway ticket']),
                'excludes'    => ['Lunch & dinner', 'Personal expenses', 'Travel insurance'],
            ],
            [
                'title'       => 'Haghpat & Sanahin Monasteries',
                'slug'        => 'haghpat-sanahin',
                'region'      => 'lori',
                'description' => "Explore two UNESCO World Heritage monasteries set in the lush forests of northern Armenia. Marvel at masterpieces of medieval Armenian architecture dating back to the 10th century.\n\nThese twin monasteries, built by rival brothers, represent the peak of Armenian religious architecture and are surrounded by breathtaking green gorges.",
                'duration'    => '1 Day',
                'price_from'  => 55.00,
                'image_url'   => 'https://images.unsplash.com/photo-1597922187945-f300350e9097?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1597922187945-f300350e9097?w=800&q=80','https://images.unsplash.com/photo-1569949237615-e1268f0b311b?w=800&q=80'],
                'itinerary'   => [['title'=>'Haghpat Monastery','description'=>'Explore the 10th-century UNESCO site with its stunning gavit, cross-stones, and panoramic views of the Debed Canyon.'],['title'=>'Sanahin Monastery','description'=>'Visit the rival monastery across the gorge, known for its academy and library. See the unique bridge of Sanahin.'],['title'=>'Alaverdi & Debed Canyon','description'=>'Drive through the spectacular Debed Canyon, stopping at viewpoints and the copper-mining town of Alaverdi.']],
                'includes'    => $defaultIncludes,
                'excludes'    => $defaultExcludes,
            ],
            [
                'title'       => 'Dilijan National Park & Goshavank',
                'slug'        => 'dilijan-goshavank',
                'region'      => 'tavush',
                'description' => "Discover the \"Armenian Switzerland\" — Dilijan's stunning forests, crystal-clear lakes, and the beautifully carved Goshavank monastery complex.\n\nWander through Dilijan's charming old quarter with restored 19th-century houses, hike to Parz Lake through ancient forests, and explore one of Armenia's most finely decorated medieval monasteries.",
                'duration'    => '1 Day',
                'price_from'  => 50.00,
                'image_url'   => 'https://images.unsplash.com/photo-1580137189272-c9379f8864fd?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1580137189272-c9379f8864fd?w=800&q=80','https://images.unsplash.com/photo-1569949237615-e1268f0b311b?w=800&q=80'],
                'itinerary'   => [['title'=>'Dilijan Old Quarter','description'=>'Explore the restored craftsmen\'s quarter with traditional architecture, artisan workshops, and cozy cafes.'],['title'=>'Goshavank Monastery','description'=>'Visit the 12th-century monastery with Armenia\'s finest khachkar — the "Aseghnagorts" (needlework) cross-stone by Pavgos.'],['title'=>'Parz Lake','description'=>'Hike through the forest to the serene Parz Lake. Optional: zip-line and boat rides.']],
                'includes'    => $defaultIncludes,
                'excludes'    => ['Meals', 'Zip-line & boat rides', 'Personal expenses'],
            ],
            [
                'title'       => 'Mount Aragats & Amberd Fortress',
                'slug'        => 'aragats-amberd',
                'region'      => 'aragatsotn',
                'description' => "Ascend Armenia's highest peak and visit the 7th-century Amberd fortress perched on a cliff between two gorges. Enjoy alpine meadows, wildflowers, and breathtaking panoramic views.\n\nThe tour includes a stop at the unique Armenian Alphabet Monument and the ancient fortress of Amberd, one of the best-preserved medieval castles in Armenia.",
                'duration'    => '1 Day',
                'price_from'  => 45.00,
                'image_url'   => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80','https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&q=80'],
                'itinerary'   => [['title'=>'Armenian Alphabet Monument','description'=>'Stop at the unique monument featuring all 39 letters of the Armenian alphabet, created by architect Jim Torosyan.'],['title'=>'Amberd Fortress','description'=>'Explore the 7th-century fortress and 11th-century church perched dramatically between two river gorges.'],['title'=>'Lake Kari (Aragats)','description'=>'Drive up to the alpine lake at 3,200m on the slopes of Mount Aragats with stunning mountain panoramas.']],
                'includes'    => $defaultIncludes,
                'excludes'    => $defaultExcludes,
            ],
            [
                'title'       => 'Gyumri Heritage Walk',
                'slug'        => 'gyumri-heritage',
                'region'      => 'shirak',
                'description' => "Explore Armenia's second-largest city with its unique black tufa architecture, vibrant arts scene, and charming old quarter. Visit the Sev Berd fortress and local craft workshops.\n\nGyumri has preserved its 19th-century character better than any city in Armenia, with elegant balconies, traditional smithies, and a deep artistic tradition.",
                'duration'    => '1 Day',
                'price_from'  => 40.00,
                'image_url'   => 'https://images.unsplash.com/photo-1595867818082-083862f3d630?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1595867818082-083862f3d630?w=800&q=80','https://images.unsplash.com/photo-1590073242678-70ee3fc28e8e?w=800&q=80'],
                'itinerary'   => [['title'=>'Gyumri Old Quarter','description'=>'Walk through the beautifully preserved 19th-century streets with black tufa buildings, wrought-iron balconies, and artisan workshops.'],['title'=>'Sev Berd Fortress','description'=>'Visit the Russian-era Black Fortress overlooking the city, now a cultural venue.'],['title'=>'Local Crafts & Cuisine','description'=>'Visit a traditional pottery workshop and enjoy Gyumri\'s famous cuisine at a local restaurant.']],
                'includes'    => $defaultIncludes,
                'excludes'    => $defaultExcludes,
            ],
            [
                'title'       => 'Echmiadzin Cathedral & Zvartnots',
                'slug'        => 'echmiadzin-zvartnots',
                'region'      => 'armavir',
                'description' => "Visit the spiritual heart of Armenia — the Holy See of Echmiadzin, the oldest state-built cathedral in the world (303 AD). Explore the ruins of the magnificent 7th-century Zvartnots Cathedral.\n\nThis tour takes you through 1,700 years of Armenian Christian history, including the treasury with the Holy Lance that pierced Christ's side.",
                'duration'    => '1 Day',
                'price_from'  => 35.00,
                'image_url'   => 'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800&q=80','https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&q=80'],
                'itinerary'   => [['title'=>'Echmiadzin Cathedral','description'=>'Visit the Mother Cathedral (303 AD), see the treasury with sacred relics including the Holy Lance. Witness the seat of the Armenian Catholicos.'],['title'=>'Zvartnots Cathedral','description'=>'Explore the ruins of this once-magnificent 7th-century cathedral, a UNESCO World Heritage Site with stunning views of Mount Ararat.'],['title'=>'Sardarapat Memorial','description'=>'Visit the memorial commemorating the 1918 Battle of Sardarapat, a defining moment in Armenian history.']],
                'includes'    => $defaultIncludes,
                'excludes'    => $defaultExcludes,
            ],
            [
                'title'       => 'Southern Armenia Adventure',
                'slug'        => 'southern-armenia-adventure',
                'region'      => 'syunik',
                'description' => "A multi-day journey through Armenia's southern highlights: Tatev Monastery, the Wings of Tatev aerial tramway, Jermuk waterfall, and the ancient caves of Khndzoresk.\n\nThis 3-day adventure covers the wildest and most dramatic landscapes in Armenia — deep gorges, mountain passes, cave cities, and ancient monasteries perched on cliff edges.",
                'duration'    => '3 Days',
                'price_from'  => 180.00,
                'image_url'   => 'https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=800&q=80','https://images.unsplash.com/photo-1608746249753-9346e2dca7c0?w=800&q=80','https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80'],
                'itinerary'   => [['title'=>'Day 1: Noravank & Jermuk','description'=>'Visit Noravank Monastery in red canyon. Continue to Jermuk spa town, visit the waterfall and mineral springs.'],['title'=>'Day 2: Tatev & Khndzoresk','description'=>'Ride Wings of Tatev tramway. Explore Tatev Monastery. Visit Khndzoresk cave village and swinging bridge.'],['title'=>'Day 3: Goris & Karahunj','description'=>'Explore Goris with its cave dwellings. Visit Karahunj (Armenian Stonehenge), a prehistoric observatory.']],
                'includes'    => array_merge($defaultIncludes, ['2 nights hotel', 'Breakfasts', 'Tramway ticket']),
                'excludes'    => ['Lunches & dinners', 'Personal expenses', 'Travel insurance'],
            ],
            [
                'title'       => 'Grand Tour of Armenia',
                'slug'        => 'grand-tour-armenia',
                'region'      => 'yerevan',
                'description' => "The ultimate Armenia experience covering all major highlights across 7 unforgettable days. From Yerevan to Tatev, Sevan to Dilijan — experience the full diversity of this ancient land.\n\nThis comprehensive tour includes pagan temples, medieval monasteries, alpine lakes, wine country, dramatic gorges, and warm Armenian hospitality at every turn.",
                'duration'    => '7 Days',
                'price_from'  => 650.00,
                'image_url'   => 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80','https://images.unsplash.com/photo-1558972250-100afca53bde?w=800&q=80','https://images.unsplash.com/photo-1600959907703-125ba1374a12?w=800&q=80','https://images.unsplash.com/photo-1603921288457-0a30e11e7db8?w=800&q=80','https://images.unsplash.com/photo-1608746249753-9346e2dca7c0?w=800&q=80'],
                'itinerary'   => [['title'=>'Day 1: Yerevan City Tour','description'=>'Republic Square, Cascade, Matenadaran, Vernissage market, evening at Opera.'],['title'=>'Day 2: Garni & Geghard','description'=>'Garni Temple, Symphony of Stones, Geghard Monastery. Lavash baking experience.'],['title'=>'Day 3: Khor Virap & Noravank','description'=>'Khor Virap with Ararat views. Drive through red canyons to Noravank. Wine tasting in Areni.'],['title'=>'Day 4: Tatev & Southern Armenia','description'=>'Wings of Tatev tramway. Explore Tatev Monastery. Overnight in Goris.'],['title'=>'Day 5: Lake Sevan & Dilijan','description'=>'Sevanavank Monastery. Lunch by the lake. Drive to Dilijan, the Armenian Switzerland.'],['title'=>'Day 6: Lori Monasteries','description'=>'UNESCO sites Haghpat and Sanahin. Debed Canyon. Return via Vanadzor.'],['title'=>'Day 7: Echmiadzin & Farewell','description'=>'Visit Echmiadzin Cathedral and Zvartnots. Farewell lunch with traditional Armenian feast.']],
                'includes'    => ['Professional guide (7 days)', 'Air-conditioned transport', '6 nights hotels (4-star)', 'Daily breakfast', 'Welcome & farewell dinners', 'All entry fees', 'Wings of Tatev ticket', 'Wine tasting'],
                'excludes'    => ['International flights', 'Lunches (except Day 7)', 'Personal expenses', 'Travel insurance', 'Tips'],
            ],
            [
                'title'       => 'Khndzoresk Cave Village',
                'slug'        => 'khndzoresk-caves',
                'region'      => 'syunik',
                'description' => "Cross the swinging bridge over the dramatic gorge to explore the abandoned cave village of Old Khndzoresk. A surreal landscape of rock pillars, ancient cave dwellings, and a hermit's chapel.\n\nThis natural fortress was inhabited until the 1950s. The swinging bridge (160m long, 63m high) offers thrilling views of the gorge below.",
                'duration'    => '1 Day',
                'price_from'  => 55.00,
                'image_url'   => 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80',
                'gallery'     => ['https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80','https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=800&q=80'],
                'itinerary'   => [['title'=>'Khndzoresk Village','description'=>'Visit the modern village and learn about the history of this unique cave settlement.'],['title'=>'Swinging Bridge','description'=>'Cross the 160-meter swinging bridge suspended 63 meters above the gorge.'],['title'=>'Cave Dwellings & Chapel','description'=>'Explore the abandoned cave homes, St. Tatevos Church, and the hermit\'s cave chapel carved into the cliff.']],
                'includes'    => $defaultIncludes,
                'excludes'    => $defaultExcludes,
            ],
        ];

        foreach ($tours as $tour) {
            Tour::create(array_merge($tour, [
                'type'     => 'ingoing',
                'featured' => true,
                'status'   => 'active',
            ]));
        }

        $this->command->info('Seeded ' . count($tours) . ' ingoing tours with full details.');
    }
}
